#ifndef __Color_GUARD__
#define __Color_GUARD__

#include <Windows.h>

// -------- DEPENDENCY CLASSES --------
	
		enum class ForegroundColour
		{
			BLACK = 0,
			DARKBLUE = FOREGROUND_BLUE,
			DARKGREEN = FOREGROUND_GREEN,
			DARKCYAN = FOREGROUND_GREEN | FOREGROUND_BLUE,
			DARKRED = FOREGROUND_RED,
			DARKMAGENTA = FOREGROUND_RED | FOREGROUND_BLUE,
			DARKYELLOW = FOREGROUND_RED | FOREGROUND_GREEN,
			GRAY = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
			DARKGRAY = FOREGROUND_INTENSITY,
			BLUE = FOREGROUND_INTENSITY | FOREGROUND_BLUE,
			GREEN = FOREGROUND_INTENSITY | FOREGROUND_GREEN,
			CYAN = FOREGROUND_INTENSITY | FOREGROUND_GREEN | FOREGROUND_BLUE,
			RED = FOREGROUND_INTENSITY | FOREGROUND_RED,
			MAGENTA = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_BLUE,
			YELLOW = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN,
			WHITE = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE
		};
		enum class BackgroundColour
		{
			BLACK = 0,
			DARKBLUE = BACKGROUND_BLUE,
			DARKGREEN = BACKGROUND_GREEN,
			DARKCYAN = BACKGROUND_GREEN | BACKGROUND_BLUE,
			DARKRED = BACKGROUND_RED,
			DARKMAGENTA = BACKGROUND_RED | BACKGROUND_BLUE,
			DARKYELLOW = BACKGROUND_RED | BACKGROUND_GREEN,
			GREY = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE,
			DARKGREY = BACKGROUND_INTENSITY,
			BLUE = BACKGROUND_INTENSITY | BACKGROUND_BLUE,
			GREEN = BACKGROUND_INTENSITY | BACKGROUND_GREEN,
			CYAN = BACKGROUND_INTENSITY | BACKGROUND_GREEN | BACKGROUND_BLUE,
			RED = BACKGROUND_INTENSITY | BACKGROUND_RED,
			MAGENTA = BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_BLUE,
			YELLOW = BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_GREEN,
			WHITE = BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE
		};
#endif